export const ChanelData = [
    {
      id: 1,
      mainImg: "./images/CHANEL/Chanel1_1.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEl/Chanel1_3.png",
      ],
      name: "CHANEL FLAP BAG",
      brandName: "CHANEL",
      code: "844931-002",
      price: "15.000.000 VND",
      new: "New",
      discount: "20%",
      sizes: [15.5, 17, 20.5, 24, 38.5, 40],
    },
    {
      id: 2,
      mainImg: "./images/CHANEL/Chanel1_2.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CHANEL SUPER GALAXY CRIMSON",
      brandName: "CHANEL",
      code: "835738-800",
      price: "1.490.000 VND",
      discount: "13%",
      sizes: [36, 36.5, 37, 38, 38.5, 39, 40],
    },
    {
      id: 3,
      mainImg: "./images/CHANEL/Chanel1_3.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CHANEL TRIPLE WHITE",
      brandName: "CHANEL",
      code: "CD5434-100",
      price: "1.900.000 VND",
      discount: "9%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 4,
      mainImg: "./images/CHANEL/Chanel1_4.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_3.png",
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
      ],
      name: "RUNNING REACT ELEMENT 87",
      brandName: "CHANEL",
      code: "AQ1090-002",
      price: "1.590.000 VND",
      discount: "11%",
      sizes: [39, 40],
    },
    {
      id: 5,
      mainImg: "./images/CHANEL/Chanel1_1.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CORTEZ BASIC GS",
      brandName: "CHANEL",
      code: "BV0014-100",
      price: "2.350.000 VND",
      discount: "15%",
      sizes: [37, 37.5, 38],
    },
    {
      id: 6,
      mainImg: "./images/CHANEL/Chanel1_2.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CHANEL LIGHT SOFT PINK MAGIC EMBER",
      brandName: "CHANEL",
      code: "CW6536-101",
      price: "1.950.000 VND",
      discount: "12.5%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 7,
      mainImg: "./images/CHANEL/Chanel1_3.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "AIR FORCE 1 SHADOW 8 BIT BLACK",
      brandName: "CHANEL",
      code: "CV8480-001",
      price: "2.790.000 VND",
      discount: "8%",
      sizes: [36.5, 37, 37.5, 38, 38.5],
    },
    {
      id: 8,
      mainImg: "./images/CHANEL/Chanel1_4.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "DROP TYPE HBR WHITE DEEP ROYAL BLUE",
      brandName: "CHANEL",
      code: "CQ0989-100",
      price: "1.290.000 VND",
      discount: "11%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38],
    },
    {
      id: 9,
      mainImg: "./images/CHANEL/Chanel1_1.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CHANEL FLAP ROSHE ONE WHITE",
      brandName: "CHANEL",
      code: "511881-112",
      price: "2.290.000 VND",
      discount: "13%",
      new: "New",
      sizes: [37.5, 38, 38.5, 39, 40],
    },
    {
      id: 10,
      mainImg: "./images/CHANEL/Chanel1_2.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "JOYRIDE RUN CC",
      brandName: "CHANEL",
      code: "AO1742-003",
      price: "1.650.000 VND",
      discount: "13%",
      sizes: [37.5, 38, 38.5, 39, 40],
    },
    {
      id: 11,
      mainImg: "./images/CHANEL/Chanel1_3.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "COURT VISION LOW HOLOGRAM",
      brandName: "CHANEL",
      code: "CW5596-100",
      price: "1.900.000 VND",
      discount: "13%",
      new: "New",
      sizes: [35.5, 36, 36.5, 38, 38.5, 39, 40],
    },
    {
      id: 12,
      mainImg: "./images/CHANEL/Chanel1_4.png",
      extraImgList: [
        "./images/CHANEL/Chanel1_1.png",
        "./images/CHANEL/Chanel1_2.png",
        "./images/CHANEL/Chanel1_3.png",
      ],
      name: "CHANEL FLAP BAG",
      brandName: "CHANEL",
      code: "DH3718-001",
      price: "2.490.000 VND",
      discount: "13%",
      new: "New",
      sizes: [36.5, 37, 37.5, 38, 38.5, 39],
    },
  ];
  
  export const DiorData = [
    {
      id: 1,
      mainImg: "./images/DIOR/Dior1_1.png",
      extraImgList: [
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 1 LOW BULLS",
      brandName: "DIOR",
      code: "553558-163",
      price: "4.900.000 VND",
      new: "New",
      discount: "13%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 2,
      mainImg: "./images/DIOR/Dior1_2.png",
      extraImgList: [
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 1 ELEVATE LOW ONYX",
      brandName: "DIOR",
      code: "DH7004-102",
      price: "4.800.000 VND",
      discount: "15%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 3,
      mainImg: "./images/DIOR/Dior1_3.png",
      extraImgList: [
        "./images/DIOR/Dior1_3.png",
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_2.png",
      ],
      name: "AIR DIOR 1 HIGH OG HAND CRAFTED",
      brandName: "DIOR",
      code: "DH3097-001",
      price: "5.900.000 VND",
      discount: "18%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 4,
      mainImg: "./images/DIOR/Dior1_1.png",
      extraImgList: [
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 1 ZOOM HIGH SISTERHOOD",
      brandName: "DIOR",
      code: "CZ1360-401",
      price: "4.400.000 VND",
      discount: "11%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 5,
      mainImg: "./images/DIOR/Dior1_2.png",
      extraImgList: [
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 4 X OFF-WHITE SAIL",
      brandName: "DIOR",
      code: "CV9388-100",
      price: "28.900.000 VND",
      discount: "13%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 6,
      mainImg: "./images/DIOR/Dior1_3.png",
      extraImgList: [
        "./images/DIOR/Dior1_3.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
      ],
      name: "AIR DIOR 1 LOW UNC 2021",
      brandName: "DIOR",
      code: "553558-144",
      price: "5.500.000 VND",
      new: "New",
      discount: "10%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 7,
      mainImg: "./images/DIOR/Dior1_1.png",
      extraImgList: [
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 1 MID LIGHT SMOKE GREY ANTHRACITE",
      brandName: "DIOR",
      code: "554724-078",
      price: "5.900.000 VND",
      discount: "8%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 8,
      mainImg: "./images/DIOR/Dior1_2.png",
      extraImgList: [
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_3.png",
        "./images/DIOR/Dior1_1.png",
      ],
      name: "AIR DIOR 1 MID GS WHITE POLLEN BLACK",
      brandName: "DIOR",
      code: "554725-177",
      price: "3.900.000 VND",
      new: "New",
      discount: "9%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 9,
      mainImg: "./images/DIOR/Dior1_3.png",
      extraImgList: [
        "./images/DIOR/Dior1_3.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
      ],
      name: "AIR DIOR 11 HIGH BRED",
      brandName: "DIOR",
      code: "378038-061",
      price: "8.500.000 VND",
      new: "New",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 10,
      mainImg: "./images/DIOR/Dior1_1.png",
      extraImgList: [
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 5 LOW FIRE RED",
      brandName: "DIOR",
      code: "314338-101",
      price: "1.500.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 11,
      mainImg: "./images/DIOR/Dior1_2.png",
      extraImgList: [
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
        "./images/DIOR/Dior1_3.png",
      ],
      name: "AIR DIOR 4 LIGHTNING",
      brandName: "DIOR",
      code: "CT8527-700",
      price: "6.900.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 12,
      mainImg: "./images/DIOR/Dior1_3.png",
      extraImgList: [
        "./images/DIOR/Dior1_3.png",
        "./images/DIOR/Dior1_2.png",
        "./images/DIOR/Dior1_1.png",
      ],
      name: "AIR DIOR 1 MID PINE GREEN MEN",
      brandName: "DIOR",
      code: "554724-067",
      price: "4.900.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
  ];
  
  export const CoachData = [
    {
      id: 1,
      mainImg: "./images/COACH/Coach1_1.png",
      extraImgList: [
        "./images/COACH/Coach1_1.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_3.png",
      ],
      name: "COACH YEEZY 350 V2 BELUGA 2.0",
      brandName: "COACH",
      code: "AH2203",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/COACH/Coach1_2.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "ZX 2K BOOST GREY SIGNAL CYAN",
      brandName: "COACH",
      code: "FX8835",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/COACH/Coach1_3.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "COACH YEEZY 350 V2 YEEZREEL",
      brandName: "COACH",
      code: "FW5191",
      price: "7.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/COACH/Coach1_4.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "COACH YEEZY 350 V2 SESAME",
      brandName: "COACH",
      code: "F99710",
      price: "9.000.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 5,
      mainImg: "./images/COACH/Coach1_1.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "ZX 2K BOOST WHITE IRIDESCENT",
      brandName: "COACH",
      code: "FV2928",
      price: "2.290.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 6,
      mainImg: "./images/COACH/Coach1_2.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "YVORI BLUE GREEN RUNNING TRAINERS",
      brandName: "COACH",
      code: "B40908",
      price: "490.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 7,
      mainImg: "./images/COACH/Coach1_3.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "COACH YEEZY 350 V2 CLAY",
      brandName: "COACH",
      code: "EG7490",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 8,
      mainImg: "./images/COACH/Coach1_4.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "COACH YEEZY 350 V2 GREEN",
      brandName: "COACH",
      code: "BY9611",
      price: "15.000.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 9,
      mainImg: "./images/COACH/Coach1_1.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "NMD R1 Y JAPAN CORE BLACK",
      brandName: "COACH",
      code: "CG6245",
      price: "1.490.000  VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 10,
      mainImg: "./images/COACH/Coach1_2.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "NMD HU PHARRELL X BILLIONAIRE BOYS CLUB MULTI-COLOR ",
      brandName: "COACH",
      code: "BB9544",
      price: "4.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 11,
      mainImg: "./images/COACH/Coach1_3.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "ULTRA BOOST 19 WHI TE BLUE",
      brandName: "COACH",
      code: "EF1340",
      price: "2.200.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 12,
      mainImg: "./images/COACH/Coach1_4.png",
      extraImgList: [
        "./images/COACH/Coach1_3.png",
        "./images/COACH/Coach1_2.png",
        "./images/COACH/Coach1_4.png",
      ],
      name: "YUNG 1 HI RES ORANGE",
      brandName: "COACH",
      code: "B37613",
      price: "2.190.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  
  export const LouisvuittonData = [
    {
      id: 1,
      mainImg: "./images/LOUISVUITTON/Lvt1.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt1.png",
        "./images/LOUISVUITTON/Lvt2.png",
        "./images/LOUISVUITTON/Lvt3.png",
      ],
      name: "LOUISVUITTON GAN DAM ESPORT",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/LOUISVUITTON/Lvt2.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt4.png",
        "./images/LOUISVUITTON/Lvt5.png",
        "./images/LOUISVUITTON/Lvt3.png",
      ],
      name: "LOUISVUITTON GENG NO WORLD",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYBW",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/LOUISVUITTON/Lvt3.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt7.png",
        "./images/LOUISVUITTON/Lvt8.png",
      ],
      name: "LOUISVUITTON T1 FIVE START",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYRW",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/LOUISVUITTON/Lvt4.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt4.png",
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt5.png",
      ],
      name: "LOUISVUITTON BOSTON",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-BT",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 5,
      mainImg: "./images/LOUISVUITTON/Lvt5.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt5.png",
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt8.png",
      ],
      name: "LOUISVUITTON SHENJU HAISIRAMA",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 6,
      mainImg: "./images/LOUISVUITTON/Lvt3.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt5.png",
        "./images/LOUISVUITTON/Lvt2.png",
      ],
      name: "LOUISVUITTON SUPER SAYAN",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 7,
      mainImg: "./images/LOUISVUITTON/Lvt7.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt7.png",
        "./images/LOUISVUITTON/Lvt4.png",
        "./images/LOUISVUITTON/Lvt8.png",
      ],
      name: "LOUISVUITTON BUILD GENIUS",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 8,
      mainImg: "./images/LOUISVUITTON/Lvt8.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt8.png",
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt1.png",
      ],
      name: "LOUISVUITTON FAIZ ACCEL",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 9,
      mainImg: "./images/LOUISVUITTON/Lvt3.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt5.png",
        "./images/LOUISVUITTON/Lvt4.png",
      ],
      name: "LOUISVUITTON AATROX DARKIN DEMON BLADE",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 10,
      mainImg: "./images/LOUISVUITTON/Lvt1.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt1.png",
        "./images/LOUISVUITTON/Lvt4.png",
        "./images/LOUISVUITTON/Lvt7.png",
      ],
      name: "LOUISVUITTON PANTHEON",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 11,
      mainImg: "./images/LOUISVUITTON/Lvt2.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt2.png",
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt7.png",
      ],
      name: "LOUISVUITTON ZED99",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 12,
      mainImg: "./images/LOUISVUITTON/Lvt3.png",
      extraImgList: [
        "./images/LOUISVUITTON/Lvt3.png",
        "./images/LOUISVUITTON/Lvt7.png",
        "./images/LOUISVUITTON/Lvt5.png",
      ],
      name: "LOUISVUITTON AURORA",
      brandName: "LOUISVUITTON",
      code: "LOUISVUITTON-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  
  export const GucciData = [
    {
      id: 1,
      mainImg: "./images/GUCCI/Gucci1.png",
      extraImgList: [
        "./images/GUCCI/Gucci1.png",
        "./images/GUCCI/Gucci3.png",
        "./images/GUCCI/Gucci4.png",
      ],
      name: "GUCCI SUEDE BLUE",
      brandName: "GUCCI",
      code: "362223-02",
      price: "2.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/GUCCI/Gucci2.png",
      extraImgList: [
        "./images/GUCCI/Gucci2.png",
        "./images/GUCCI/Gucci4.png",
        "./images/GUCCI/Gucci5.png",
      ],
      name: "GUCCI THUNDER SPECTRA",
      brandName: "GUCCI",
      code: "367516-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/GUCCI/Gucci3.png",
      extraImgList: [
        "./images/GUCCI/Gucci3.png",
        "./images/GUCCI/Gucci4.png",
        "./images/GUCCI/Gucci5.png",
      ],
      name: "GUCCI THUNDER 4 LIFE",
      brandName: "GUCCI",
      code: "367516-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/GUCCI/Gucci4.png",
      extraImgList: [
        "./images/GUCCI/Gucci4.png",
        "./images/GUCCI/Gucci2.png",
        "./images/GUCCI/Gucci1.png",
      ],
      name: "GUCCI RS-X RETRO RED GREY INDIGO",
      brandName: "GUCCI",
      code: "371511-01",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
  
    {
      id: 5,
      mainImg: "./images/GUCCI/Gucci5.png",
      extraImgList: [
        "./images/GUCCI/Gucci5.png",
        "./images/GUCCI/Gucci4.png",
        "./images/GUCCI/Gucci3.png",
      ],
      name: "GUCCI RSX TRACKS JR",
      brandName: "GUCCI",
      code: "369629-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 6,
      mainImg: "./images/GUCCI/Gucci6.png",
      extraImgList: [
        "./images/GUCCI/Gucci6.png",
        "./images/GUCCI/Gucci1.png",
        "./images/GUCCI/Gucci3.png",
      ],
      name: "GUCCI RSX WHISPER WHITE",
      brandName: "GUCCI",
      code: "369329-03",
      price: "3.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 7,
      mainImg: "./images/GUCCI/Gucci7.png",
      extraImgList: [
        "./images/GUCCI/Gucci7.png",
        "./images/GUCCI/Gucci2.png",
        "./images/GUCCI/Gucci5.png",
      ],
      name: "GUCCI RSX HARD DRIVE",
      brandName: "GUCCI",
      code: "370644-03",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 8,
      mainImg: "./images/GUCCI/Gucci8.png",
      extraImgList: [
        "./images/GUCCI/Gucci8.png",
        "./images/GUCCI/Gucci3.png",
        "./images/GUCCI/Gucci4.png",
      ],
      name: "GUCCI RS-X REINVENTION",
      brandName: "GUCCI",
      code: "369579-02",
      price: "3.600.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 9,
      mainImg: "./images/GUCCI/Gucci9.png",
      extraImgList: [
        "./images/GUCCI/Gucci9.png",
        "./images/GUCCI/Gucci1.png",
        "./images/GUCCI/Gucci2.png",
      ],
      name: "GUCCI RS-X TOYS",
      brandName: "GUCCI",
      code: "369628-02",
      price: "3.600.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  